/** 自参考图瓣轴采样 — 边界色已人工回正；重生成: python scripts/extract_plutchik_palette.py */
export const PLUTCHIK_WHEEL_SEGMENT_FILL: Record<string, string> = {
  joy_ecstasy: '#f4d456',
  joy_joy: '#f6d356',
  joy_serenity: '#fcedb4',
  trust_admiration: '#6edb8a',
  trust_trust: '#6bdb89',
  trust_acceptance: '#b8efcf',
  fear_terror: '#5abba8',
  fear_fear: '#67cdb6',
  fear_apprehension: '#9dd8cf',
  surprise_amazement: '#62a9eb',
  surprise_surprise: '#62a9eb',
  surprise_distraction: '#b5ddf7',
  sadness_grief: '#597ae1',
  sadness_sadness: '#9b63e2',
  sadness_pensiveness: '#c5b8ef',
  disgust_loathing: '#9d62e0',
  disgust_disgust: '#b06cd8',
  disgust_boredom: '#ddb8f0',
  anger_rage: '#eb5a62',
  anger_anger: '#eb666b',
  anger_annoyance: '#fac8c8',
  anticipation_vigilance: '#f08c3a',
  anticipation_anticipation: '#eb8945',
  anticipation_interest: '#ffd4a8',
  dyad_love: '#fef7e4',
  dyad_submission: '#e4f8ed',
  dyad_awe: '#e3f7f5',
  dyad_disapproval: '#e0e8fa',
  dyad_remorse: '#e8dcf8',
  dyad_contempt: '#f3e7f3',
  dyad_aggression: '#fce8e7',
  dyad_optimism: '#fcf0e2',
}
